### ISSUE TITLE
DB layer currently allows faculty members to be programatically created with no Area attached

### ISSUE THREAD

**Issue by rmainseas** [seas-computing/course-planner#151]
### Description
It is currently possible to create a faculty member who exists outside of any area.

### To Reproduce

1. Call `Repository<Faculty>.create()` with no `area` field

### Expected Behavior

An exception should be thrown by the DB layer indicating that `areaId` is a required field (or similar).

### Actual Behavior

The faculty member is successfully created

### Additional Information

I ran into a similar issue working with courses and areas as part of #135. The solution is to add `{ nullable: false }` as a third parameter of the `@ManyToOne` relation decorator

**Comment by jonseitz** [comment]
Resolved by #284
