### ISSUE TITLE
Refactor API functions to use global axios instance

### ISSUE THREAD

**Issue by rmainseas** [seas-computing/course-planner#154]
The usage of a global `axios` instance would allow us to set certain base configuration options such as `baseURL` so that API calls would be to endpoints like `users` or `courses` instead of `/api/users`. 

For example:

```js
// api.js
import { create } from 'axios';
​
const api = create({
  baseUrl: `//${window.location.host}/api`, //Whatever our API base URL might be - I'm totally making that up.
  headers: { ['X-Requested-With']: 'XMLHttpRequest' },
  transformResponse: [
    (data, err) => {
        // use err to display new error message toast
    }
  ]
});
​
export const { get, post } = api;
```

API calls can now be implementing something like the following:

```js
import { get } from 'api';

export const getCurrentUser = (): AxiosPromise<UserResponse> => request.get('users/current');
```

With that we now get:

- "Automatic" handling of errors returned by the API. So a 404, or a 403 returned by the API can be automagically turned into an error message popup on the client with no additional action required
- The ability to use shorter URLs in API calls. So `/api/users/current` just becomes `users/current`. Not a HUGE thing, but it's nice to to have to re-type `/api` multiple times everywhere.

**Comment by jonseitz** [comment]
This was implemented in #234, using a global `axios` instance to automatically add our `/course-planner` prefix for all requests.
