### ISSUE TITLE
Application default view does not show course admin view

### ISSUE THREAD

**Issue by rmainseas** [seas-computing/course-planner#162]
### Description
When opening the application, the application should show the course admin view by default

### To Reproduce

1. Open the application

### Expected Behavior

The course admin view should be displayed

![image](https://user-images.githubusercontent.com/50675045/76624892-8a264c00-650c-11ea-83b3-fd76856ded02.png)

### Actual Behavior

A blank page is displayed

![image](https://user-images.githubusercontent.com/50675045/76624765-4a5f6480-650c-11ea-99f3-4aa169a2dd83.png)

### Platform:

- **Platform Type:** Desktop
- **OS:** Debian
  - **Version:** 9
- **Browser:** Chrome
  - **Version** `Version 80.0.3987.87

### Additional Information

---

- [ ] Test
- [ ] Docs

**Comment by jonseitz** [comment]
This was resolved by #217, since it's the course instance table that should appear as the default landing page, not the course admin.
