### ISSUE TITLE
Area colors are hard coded into mark one and cannot change with the database

### ISSUE THREAD

**Issue by rmainseas** [seas-computing/course-planner#164]
Area colors are currently [set in mark-one](https://github.com/seas-computing/mark-one/blob/develop/src/Theme/MarkOneTheme.ts#L103-L116). Going forward this means that the list of areas in the database, and in mark-one will have to be kept in sync. when setting things like table cell colors etc.

A much better option would be to store the area color in the database beside the area. This could then be set as a required field and users could then pick a color when creating an area.

**Comment by jonseitz** [comment]
The hard-coded area colors are meant to match the "official" SEAS color palette from the website, so we don't want to make those customizable at this time
