### ISSUE TITLE
Refactor course admin controller to move queries into a service method and return data in a sorted fashion.

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#177]
Dependant on #178 

- [ ] Move course admin queries out of controller and into a separate service method.
  - Look at implementation in Course instance controller.
- [x] Alter queries so that courses are returned sorted first by area then by compound course prefix/number field.
  - [x] Ideally those courses that have no number (e.g. Seminars, or courses like 'ES 1XX' should be displayed last) 
  - [x] Do not return numeric element of course number field.
- [ ] Tests
- [ ] Docs

**Comment by jonseitz** [comment]
Duplicates #192 and #616.
