### ISSUE TITLE
Usage of aliased paths in mark-one breaks course planner and prevents the tests from running

### ISSUE THREAD

**Issue by rmainseas** [seas-computing/course-planner#191]
### To Reproduce

1. `git checkout develop`
1. `npm run test`

### Expected Behavior

The tests should run

### Actual Behavior

The process crashes, saying that it can't find module `Buttons`.

### Additional Information

I suspect it may be related to our usage of non-relative paths like so: https://github.com/seas-computing/mark-one/blob/develop/src/Modals/ModalHeader.tsx#L8

---

- [ ] Test
- [ ] Docs

**Comment by jonseitz** [comment]
This specific instance was resolved by seas-computing/mark-one#57, though this is something we'll want to watch for in code-review on mark-one in the future.
