### ISSUE TITLE
Course instance table for courses interface

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#195]
This issue provides a read-only view of the course instance data for the Courses Interface, as provided by #98.

Includes:
- [ ] Table (all the columns)
- [ ] Data for current academic year
- [ ] Docs
- [ ] Tests

Does not include:
* Rooms, times and faculty columns
* Edit functionality for fields
* Sorting and filtering fields in the headers
* Background fetching of data
* Ability to move between academic years 
* Notes and details modals for Course model
* Courses report
* View customization

**Comment by jonseitz** [comment]
Resolved by #217
