### ISSUE TITLE
Implementation of "Room / Time" column for course instance table

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#196]
See https://seas-computing.github.io/course-planner_ux/courses-ncm.html# for example implementation.

* [ ] Implementation of room / time column in course instance table in courses interface
* [ ] Adjust course instance GET DTO to include campus
* [ ] Tests for conditional rendering

Does not provide:
* Ability to edit rooms / times

**Comment by jonseitz** [comment]
Resolved by #221
