### ISSUE TITLE
Refactor API routes to use global prefix

### ISSUE THREAD

**Issue by rmainseas** [seas-computing/course-planner#205]
Following @jonseitz's work on #199, we can now configure a global route prefix (such as `/api`), because the serving of the front-end files is now handled by a dedicated module, we no longer have to worry about breaking routing for that. 

This means, that we can refactor our controller decorators to remove the `/api` and add a global route prefix to the global application startup config.

**Comment by jonseitz** [comment]
Closed as duplicate of #109
