### ISSUE TITLE
Implementation of 4 year plan (multi-year plan) table

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#207]
This ticket provides:

- [ ] 4 year plan page component
  - Just a `<div />`
- [ ] 4 year plan table component
  - Using table component from Mark-One
- [ ] Populates table with initial load
  - [ ] Get data from #179   
- [ ] React route
  - /multi-year-plan
- [ ] Docs
- [ ] Tests
  - Router tests on app.tsx (does the component render at the path)

Does not provide:
* Table header functionality (such as search or filtering)

**Comment by jonseitz** [comment]
Implemented in #227
