### ISSUE TITLE
Faculty Interface - Initial table view

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#208]
This ticket provides:

- [x] Faculty page component
  - Just a `<div />`
- [x] Faculty table component
  - Using Mark-One table component
- [x] Populates table with initial load
  - [x] Get data from #198
  - [x] Just current academic year   
- [x] Add in FontAwesome icon for "Detail" column, but with no action
- [x] React route
  - /faculty
- [x] Docs
- [x] Tests
  - Router tests on app.tsx (does the component render at the path)

Does not provide:
* Background loading of additional academic years
* Add or edit sabbatical functionality (so no icons) 
* Table header functionality (such as search or filtering)

**Comment by jonseitz** [comment]
Implemented in #219
