### ISSUE TITLE
Non class meeting controller - initial GET

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#210]
API route to deliver Non-class meetings interface DTO object. Initial load delivers current default academic year.

  - Client will initially request non-class meetings with the query parameter of 'year', which will be the current academic year determined by local user's date.
  - GET request may need additional filtering and expanding to construct the response model.

  - [x] API route should expect a 'year' parameter
  - [ ] Server returns all non-class meetings
    - [ ] Within each non-class meeting is queried the parameter academic year's non-class meeting instances
    - [ ] Returns an object with a top-level field of the parameter academic year, which itself contains an array of the DTO objects.
  - [ ] If year parameter is not present then return all objects (for the purpose of background loading additional academic years.
  - [x] Sort by area
  - [ ] Docs
  - [ ] Tests

**Comment by chrxr** [comment]
Maybe we should review the positioning of 'expected size ' with Patrick. Should expected size be on the top level meeting object or on the individual meeting?

**Comment by jonseitz** [comment]
Resolved by #232
