### ISSUE TITLE
Faculty Admin interface: create new / edit modal

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#214]
See modal mockup in https://seas-computing.github.io/course-planner_ux/manage_faculty.html
Utilises modal component from MarkOne. https://seas-computing.github.io/mark-one/#/Modals

* [x] Create faculty modal opens a blank form
  * "Joint with" field will actually just be a plain text field
  * "Joint with" field will drop below "category"
  * "Category" drop-down populated with list of categories
  * "Areas" drop-down populated with list of all the areas
  * Clicking "Create" submits the form via existing POST method (#97)
    * Table updates with new faculty on successful submit
* [x] Edit faculty modal opens a populated form
  * Table updates with new faculty details on successful submit
* [x] Docs
* [x] Tests
* [x] [Accessible modal, references and examples](https://github.com/seas-computing/course-planner/issues/214#issuecomment-627472321)
  * [Modal width, required information and error messages](https://github.com/seas-computing/course-planner/issues/214#issuecomment-649003873)

**Comment by jonseitz** [comment]
Resolved by #235
