### ISSUE TITLE
Move ENUMs from entities to common directory

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#216]
In order to make ENUMs available to client for populating dropdowns and modals, need to make sure that all relevant ENUMs are in common directory rather than with the specific entities. Will involve updating import statements. May also need to make ETL statements.

* "Is seas" e.g. EPS, Yes, No (currently a bool but might need to change to an ENUM. TBC)
* Faculty absence reasons

**Comment by jonseitz** [comment]
Resolved by #225
