### ISSUE TITLE
Refactor multi-year plan (4 year plan) to deliver sorting and empty semester objects where courses are not actually offered.

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#222]
In order to lay out the 4 year plan table, we need to reliably determine the headings and position of the course instances in the table without too much client side processing. Therefore we will add in semester objects with empty faculty arrays where courses are not technically offered in a semester. The semesters will then be sorted by calendar year  then by academic year.

**Comment by jonseitz** [comment]
Implemented in #226
