### ISSUE TITLE
Course admin table text filter fields

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#224]
- Utilizes mark one text input component
- Visually/stylistically the input will be part of the header cell, but will actually be on a separate row below the table head cell.
- Requires a hidden label for accessibility that tells user what will happen each key is pressed.
- State for the input field will change on each key press.
- OnChange should filter table by the column header under which it is placed using the input field state.

- [ ] Tests
- [x] [Accessibility](https://github.com/seas-computing/course-planner/issues/224#issuecomment-635308524) - 1 hour
- [ ] Docs

**Comment by jonseitz** [comment]
Implemented in #277
