### ISSUE TITLE
QA site deployment templates

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#228]
## Course Planner QA Deployment

- I had previously worked on a cloudformation template to deploy
  containers on Fargate, and I'm going to review and as necessary
  revise that script for the course-planner app.

- Outside of Fargate, we'll need to have our Aurora/Postgres and
  ElasticCache/Redis instances configured. I'm going to work on
  cloudformation templates for those as well.

- We also discussed the need to manage credentials within the
  containers. We can use environment variable set from the AWS console
  and maintained in LastPass, but we may want to consider using on of
  AWS's management options

- Once those templates are ready for review, I'm going to push them to
  github.huit and submit a PR.

- For testing, we'll first launch everything in the sandbox account,
  before we do so in prod.

## Docker Config

We actually spent most of our time taking about the build process for
the project, and how the Docker container handles both the client and
server code. Faras raised the point that having the server and client in
the same container can be a little harder to understand logically, and
that running them from separate containers could make it easier to
monitor and manage in production. I also think there's a benefit for
development, since it could allow us to handle code rebuilds and hot
reloading for the two sides of the project separately.

- I don't want to slow our development velocity, but I'm going to look
  into how much work it would take to split then container into two, and
  see where we might be able to fit that into a sprint.

- Faras also brought up our lack of comprehensive documentation around
  the build process, so I'm going to work on writing up more notes about
  that.

## Open Question

We still need to establish a procedure for deploying, updating, and
managing containers on Fargate, and who will be responsible for the
different parts of that process. That conversation should probably
include everyone on the developer and systems teams so we're all on the
same page.

**Comment by jonseitz** [comment]
Necessary code changes in this repo were made in #234, and the templates themselves are at: https://github.huit.harvard.edu/SEAS/aws_devops/tree/main/cloudFormation/ecs-fargate
