### ISSUE TITLE
Course admin interface: create new / edit modal

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#229]
See modal mockup in https://seas-computing.github.io/course-planner_ux/manage_courses.html
Utilises modal component from MarkOne. https://seas-computing.github.io/mark-one/#/Modals

* [x] Create Course modal opens a blank form
  * "Same as" is just plain text, without the + sign
  * Undergraduate is false by default (ask Kathy and Patrick about whether it should be true)
  * "Areas" drop-down populated with list of all the areas
  * Look at stacking all fields
  * Change buttons from "Create" to "Save"
  * Clicking "Save" submits the form via existing POST method (#135 )
    * Table updates with new faculty on successful submit
* [x] Edit faculty modal opens a populated form
  * Table updates with new faculty details on successful submit
  * Clicking "Save" submits the form via existing PUT method (#136)
* [x] Implement Dropdown refactor changes on both this and faculty admin modals.
* [x] Docs
* [x] Tests
* [x] [Accessibility](https://github.com/seas-computing/course-planner/issues/214#issuecomment-627472321)

**Comment by jonseitz** [comment]
Implemented by #272
