### ISSUE TITLE
Mark-One: Refactor Dropdown component

### ISSUE THREAD

**Issue by natalynyu** [seas-computing/course-planner#233]
- [x] Refactor `Dropdown` component to match the CSS grid formatting of the `Text Input` component
- [x] If field is required then the label should include red asterisk.
- [ ] Highlight field in red on error
- [x] Display error message below the field.
- [x] `Label` should be integrated into the `Dropdown` component so that you cannot use the `Dropdown` component without providing label text
- [x] Move `Dropdown` component into the `Forms` directory
- [x] Docs
- [x] Tests

**Comment by jonseitz** [comment]
Resolved by seas-computing/mark-one#66
