### ISSUE TITLE
Implementation of HarvardKey authentication

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#238]
This ticket implements sending requests to HarvardKey for authentication, receiving requests and processing for appropriate authorization via group membership.

* Client needs to initiate the authorization.
* If user isn't logged in, they are redirected to HarvardKey login
* When user logs in create cookie in client, log cookie and groups in redis as a session for the user.
* Need to be able to clear the cookie in redis when the sessions expires. Need to sync Redis session expiration with the client.
* If user tries to log in but is not present in any Grouper Groups, redirect to somewhere saying they can't access the app. (Unless this can be dealt with on HK side.)
* Make sure that cookie set in client is valid or use on both client and server.

* [ ] Tests
* [ ] Docs

**Comment by jonseitz** [comment]
Resolved by #263
