### ISSUE TITLE
Mark One: Checkbox and Radio button component

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#239]
Need to implement a checkbox group component that can be used to wrap multiple checkboxes and display a validation message below the checkboxes. Should use HTML fieldgroup element that can receive an error message.

We will stick with a black implementation of both checkboxes and radio buttons.

- [x] Docs
- [x] Tests

**Comment by jonseitz** [comment]
Implemented in seas-computing/mark-one#72
