### ISSUE TITLE
Change 4-year plan to display and sort by catalog prefix rather than Area

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#240]
4-year plan interface needs to display and sort courses by the catalog prefix, rather than area.

* Remove the area column from the table
* Don't request area as part of the initial GET
* Change initial GET to request catalog prefix as separate field from Course number
* Implement new Catalog Prefix column
  * Catalog prefix is the first set of letters in the course number field.
  * Broken out into separate catalog prefix field in the database already
* Initial sort of table should be on Catalog Prefix
* Colors for the catalog prefixes should match the color for the area that contains the majority of the courses with that prefix.
  * Freshman Seminars (frsemn) should be the same color as SEMINAR
  * Gened should use the GENERAL color

**Comment by jonseitz** [comment]
Resolved by #265
