### ISSUE TITLE
Faculty area is not currently a required field in the database

### ISSUE THREAD

**Issue by rmainseas** [seas-computing/course-planner#251]
### Description

The database currently allows faculty members to be created with no area attached, this means that invalid data can potentially be entered into the schema and cause issues with the code

### To Reproduce

1. Using a database GUI of your choice, create a faculty member with no area ID 

### Expected Behavior

The new record should be rejected by the database engine as invalid

### Actual Behavior

The new record is accepted, as `areaId` is nullable.

---

- [ ] Test
- [ ] Docs

**Comment by jonseitz** [comment]
Resolved by #248 and seas-computing/course-planner-etl#36
