### ISSUE TITLE
Faculty table: Sabbatical / Leave modal

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#252]
When clicking on the "edit" icon for a faculty member in a semester, modal displays allowing selection of absence type, using absence type ENUM. The "present" option in the dropdown should be represented by "None", and if this is selected, nothing is shown in the table (as with current Course planning app).

Below dropdown is Cancel, and Save buttons.

Clicking 'Cancel' closes the modal with no changes. 

Clicking 'Save' closes the modal, saves the changes on that semester and updates the faculty table.

Need to check that the update method in the controller cascades down to absences table.

**Comment by jonseitz** [comment]
Implemented in #276
