### ISSUE TITLE
Schedule Initial GET

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#259]
This ticket provides the initial GET request required to populate the Schedule interface. The initial GET will only get the current semester. Later semesters can either be lazy-loaded or loaded synchronously when a user selects the semester from the sidebar dropdown.

- The GET needs to get all of the SEAS and EPS courses and course instances for a semester.
- The course needs the following associated meta data:
  - Catalog prefix and number (e.g. ES 51). These should be provided separately, as catalog prefix will be used for filtering, separate from the number.
  - Graduate / Undergraduate status (for filtering). If isUndergraduate == false, then we are assuming a course is a graduate course.
- Each course instance needs the following associated meta data:
  - The day, time and room for each meeting of the course in that semester (e.g. Monday, 10:30am - 11:45am, MD 203)
  - The campus that the rooms are in (e.g. Allston or Cambridge). This is for filtering.

We will also need to include the appropriate color for each catalog prefix. These colors are being defined in the 4 year plan ticket #240 .

**Comment by jonseitz** [comment]
Resolved by #275
