### ISSUE TITLE
Update mark-one documentation (Checkbox, Dropdown, and TextInput components) to use POSITION enum for labelPosition prop

### ISSUE THREAD

**Issue by natalynyu** [seas-computing/course-planner#267]
The documentation for the Checkbox, Dropdown, and TextInput components currently use string values (e.g. "top", "left", etc.) for the `labelPosition` value. This makes it unclear to the user that they should be using the `POSITION` enum values in their implementation.

**Comment by jonseitz** [comment]
Looks like this was resolved in seas-computing/mark-one#75
