### ISSUE TITLE
Schedule table initial view

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#273]
This ticket implements the initial view of the Schedule table: https://seas-computing.github.io/course-planner_ux/schedule.html

Included is:
* The table itself
* Blocks for each of the catalog prefix timeblocks
* Course prefix heading on each block
* Lists of course numbers within the timeblocks
- [x] [Accessibility / aesthetics check with Vittorio](https://github.com/seas-computing/course-planner/issues/273#issuecomment-732271793)
* Colors should follow those defined in the 4-year-plan

Does not include:
* Side-bar filters
* Catalog prefix filters
* Pop-ups for courses instances across the calendar

**Comment by jonseitz** [comment]
Resolved by #280
