### ISSUE TITLE
Meeting with no room breaks front end application

### ISSUE THREAD

**Issue by rmainseas** [seas-computing/course-planner#297]
### Description

An meeting with no room causes the front end to crash disruptively resulting in a white page of death. This is especially evident when re-populating the database from migrations/ETL code which doesn't bring in meeting location data. In turn, the front end tries to access `meeting.room.name`, and falls apart when it can't get `name` of `null`.

### To Reproduce

1. Create a new meeting (in the database)
2. Attach no room data to the meeting
3. Load the front end

### Expected Behavior

The meeting should be listed, but with no room attached

### Actual Behavior

The entire front end crashed to a white page

### Platform:

- **Platform Type:**  Desktop
- **OS:**  Debian
  - **Version:** 10
- **Browser:**  Chrome
  - **Version**  87

- [ ] Test
- [ ] Docs

**Comment by chrxr** [comment]
* Update and merge in https://github.com/seas-computing/course-planner-etl/tree/feature/196-room-data to allow dummy room data to be loaded into the database.
* Update front-end so that it doesn't crash if there is no room data for a course instance

**Comment by jonseitz** [comment]
Resolved by #301
