### ISSUE TITLE
Meeting Controller: PUT requests

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#304]
This ticket delivers a controller for the meeting object that allows PUT requests in order to create and/or update course instance and / or non-class meeting instance times and rooms.

* [ ] Controller:
  * Allowed roles: admin, privileged
* [ ] Service method to perform update utilizing the ORM.
   * Include validation that the submission does not break the laws of time and space (e.g. end time before start time).
   * Validate that rooms associated with submitted meeting times are not double booked in the same semester / academic year.
     * Query for any course that has a meeting with the specific room where the times overlap. 
   * Return validation errors as appropriate

**Comment by chrxr** [comment]
Pull out code from Robert's PR #232 in order to finalize this ticket.

**Comment by jonseitz** [comment]
Resolved by #333
