### ISSUE TITLE
Courses table: Room booking modal furniture

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#305]
When the edit icon in the "Meetings" column in the course instance table is clicked, open a modal using the Mark One modal component.

Includes:

* [x] Modal header, with title in the format of "Rooms for {catalog prefix and number, e.g. CS 50} - {course title, e.g. }"
* [x] Modal footer, including Cancel button
  * Clicking cancel button closes the modal
* [x] Modal body, including CSS Grid for interior components

**Comment by chrxr** [comment]
Changing the layout of this to have just two divs instead of three, one for each side. The left side will contain both the meeting times block and the faculty notes as one big scrolling div, though the meeting time block title will be frozen at the top.

**Comment by jonseitz** [comment]
Implemented in #313 & #319
