### ISSUE TITLE
Room/time booking modal: meeting / faculty notes

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#306]
Implements placing the faculty notes for the course instance in the Room Booking modal.

* [ ] Update course instance GET request to bring in faculty notes for each course instance.
* [ ] Implement faculty notes in modal.
  * Faculty notes are stored on the faculty entity
  * This feature brings in the notes for each member of faculty who is associated with the course instance, under the heading Faculty Notes. 
  * Include faculty name, with their notes below.
  * If there are no faculty for a course instance, still display "Faculty notes" header but with nothing below.

**Comment by jonseitz** [comment]
implemented in #321
