### ISSUE TITLE
Meeting request and response DTOs

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#307]
* [ ] Request DTO
  * Will need to both update and create meeting instances (ORM should be able to handle this on its own)
  * Course instance / non-class meeting IDs. 
  * Meeting IDs for the existing meetings.
  * Day/Time for each meeting instance being added/updated (required)
  * Room ID (optional)
* [ ] Response DTO
  * Sends data to update the courses / non-class meetings table with changes.
  * Table should only update the row that has changed in the selected academic year.

**Comment by chrxr** [comment]
Remove "Add Room" functionality as not in MVP.

**Comment by jonseitz** [comment]
Resolved by #310/#315
