### ISSUE TITLE
Room Controller: Initial GET

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#311]
This issue provided the initial GET for the rooms in the meetings modal for both the courses and non-class meetings tables.

The GET request will include the following details in the URL parameters:

* Start time
* End time
* Day
* Semester
* Academic year

The response will provide a list of all the rooms, including:

* Campus
* Building
* Room name
* Capacity
* Array of course titles / non-meeting names for which this room is already assigned in the time being provided by the GET request.

We will attempt this without optimization. If the queries are very slow, then we will look at how it can be optimized.

**Comment by jonseitz** [comment]
Implemented in #334
