### ISSUE TITLE
Room response DTO

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#312]
This issue provides the response DTO to model the response for when the Meetings modal requests the list of rooms.

The request will include the following data in the URL parameters:

* Start time
* End time
* Day
* Semester
* Academic year

The response should include:

* Campus
* Building and room concatenated 
* Capacity
* An array of all the course titles / non-class meetings names for which this room is booked between the start and end times provided in the GET request
* Room object ID

**Comment by jonseitz** [comment]
Resolved in #314
