### ISSUE TITLE
Room booking modal: Meeting time initial population

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#317]
This ticket provides:

* Title above the meeting times block, e.g. "Meeting times for AC 209a"
* Meeting times container block
* Loading of existing meetings into table (data already in main course instance / non-class meetings table)
* Delete and edit icons on the left and right of each line, but not their functionality
* "Add new time button", but not its functionality

**Comment by jonseitz** [comment]
Resolved by #336
