### ISSUE TITLE
Room booking modal: Bootstrap the rooms table on the right

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#332]
This ticket provide an initial implementation of the rooms table in the room booking modal with a hard coded request, to facilitate the creation and styling of the table.

As part of this ticket, we will implement the communication of the date and time from the parent component to the room table component. For now these props values will be hard coded at the parent level. As part of #316 we will implement the handing of the data from the left -> parent -> right.

It will also include the initial sorting of the table data by:
* Campus, then
* Building, then
* Room

It will not provide:

* Filtering dropdown for availability column
* Functionality of the ADD button.

**Comment by jonseitz** [comment]
Resolved by #350
