### ISSUE TITLE
Room booking modal: "Add" room button

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#353]
This ticket implements the "add" room button in the rooms table as part of the room booking modal.

This ticket implements a state field representing the currently selected room for the meeting being edited.

This ticket will also implement the functionality to disable the "add" button for the room that is currently selected for a specific meeting.

If the room selected state field is blank, then clicking add populates it. If there is already data in that state field, clicking add replaces it.

After clicking "add" the data fields with the time and date for the meeting should be cleared, resulting in rooms table returning to its cleared state.

**Comment by jonseitz** [comment]
Implemented by #365
