### ISSUE TITLE
Room booking modal: Availability filter

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#354]
This ticket implements the filtering of the rooms table in the room booking modal based on the selection in the "availability" filter drop-down.

Options:

- All: Show all rooms regardless of availability.
- Available: Show all rooms that **are not** currently selected for another course / meeting at that time and date, including "Check availability" rooms.
- Not available: Any rooms that **are** currently selected for another course / meeting at that time and date.

**Comment by jonseitz** [comment]
Resolved by #357
