### ISSUE TITLE
Room booking modal: Save changes

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#367]
This ticket provides the functionality to save any changes made using the room booking modal.

On clicking the "Save" button:

* Client side validation will run (already implemented)
* Kicks off PUT request to API endpoint
* Loading spinner is shown whilst request is in process (overlaid over the modal)
* Handle any server side validation errors that come back (server side validation already in place)
* Server side error messages will be displayed, stacked, just above the footer component in the modal. They will utilize the same styles as the other validation error messages in the modal.
  * Error message for room booking conflict will be of the format, "[Room name] is not available at [time and day]"
* On error, user expected to fix then press "save" again.
* On successful save, update list of meetings in main table with returned array of new / amended meetings.
* Close modal

This ticket also implements the PUT request method on the client side.
The request should follow the DTO as defined.

**Comment by jonseitz** [comment]
Implemented in #383
