### ISSUE TITLE
Mark One: Create global message component

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#369]
This ticket provides the design and implementation of a global message component in Mark One.

The global message component will:

* Display as an overlay at the bottom of the screen. It will overlay anything else. (highest Z-index)
* It will be able to display multiple variants of message, including:
  * Success messages (e.g. confirming a save), as in https://github.com/seas-computing/course-planner/issues/367#issue-947705082
  * Error messages (e.g. operation failed, server-side error etc.)
* Success and error messages should be styled as defined by our success and error styles in Mark One. Note difference with design, bar should use our solid colors in mark one, button may use Neutral color scheme.
* Include a "Close" button, utilizing the Mark One button component, handler passed in as a prop.

@Vittorio2015 to provide [mock-ups](https://github.com/seas-computing/course-planner/issues/369#issuecomment-888303007), think about how the [interaction between error messages and other components](https://github.com/seas-computing/course-planner/issues/369#issuecomment-890996608) on the screen might work (e.g. do other components become inactive when an error message is present?)

**Comment by Vittorio2015** [comment]
## August 2 sprint review

System error message in Courses tab - screen capture of modal triggered by system error upon user interaction (i. e., select term year from drop-down, or any other links)
![image](https://user-images.githubusercontent.com/12190138/127328762-31a8a80c-a71f-4d62-ac8d-ca1188967d18.png)

**Comment by Vittorio2015** [comment]
## Alert message interaction guidelines
* Activity example - Upon user interaction
* Interface examples – modals (i.e., course meetings, notes, etc.), tab interfaces (i.e., course of calendar display filters)
* Alert behavior
  * Alerts is persistent in modals and in tab interfaces
  * Components remain active when an error message is present
  * Alerts it may replace previous alerts (i. e., from warning to success upon user interaction)
  * Alerts are persistent  (no “close” button) until:
    * Next tab interface is shown
    * Next tab activity is rendered (new term, filtering)
    * Modals are closed
 * Alert types
    * Success
    * Warning
    * Info?
* Alert content
  * Single of numerous messages (alerts don’t stack) of same alert type (i. e., warning messages) within an alert component
* Alert dynamics
  * Situation 1 sequence – (1) System error occurs, (2) warning alert with system error notice, (3) user activity, (4) second system error occurs, (5) second system error notice added to the first one
  * Situation 2 sequence – (1) System error occurs, (2) warning alert with system error notice, (3) no user activity, (4) second system error occurs, (5) second system error notice added to the first one
  * Situation 3 sequence – (1) System error occurs, (2) warning alert with system error notice, (3) user activity, (4) successful activity outcome, (5) success alert with successful activity outcome replaces warning alert (?)
