### ISSUE TITLE
Instructor Modal: PUT endpoint

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#379]
* /api/course-intances/id/instructors
* Taking the courses instance ID and list of instructors
* Service method that gets the existing course instance, updates the list of instructors and then resaves it.
* Ensure that the order is preserved in the join table.
* Will return the new list of instructors

Validation:
* Make sure instructors are not used multiple times
* Ensure that instructors actually exist.

**Comment by jonseitz** [comment]
Implemented in #401
