### ISSUE TITLE
Ensuring SameAs courses can have the same rooms booked

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#388]
We need to ensure that courses that are the same (e.g. CS109a, AC209a, STATS 121a) may have the same room booked.

In order to do this, we will expect one of the courses to be the canonical course, and the other courses will have their "Same As" field set to that course.

Whenever a query is made to get course instance objects, we will first check the "Same As" field. If this is present, then we will get course instances for that course instead. Otherwise, we will get course instances for the original course.

If changes are made to the course instance on a "Same As" course, these will be reflected on any other related "Same As" courses.

We will not allow setting the "Same As"  field to point to a course that already has a "Same As" defined. This is to prevent circular dependencies.

To do:
* Change "Same As" field in the "Courses admin" to be a autocomplete drop down select box, displaying the course prefix and number.
* This will establish a foreign key relationship between the orginal course and the "same as" course.
* Validate that a course set as "Same as" does not already have a "Same As" relationship set.

Questions for Patrick and Sarah:

* Is this an appropriate workflow?
* Would they want anything on these "Same as" courses to be different between the courses? E.g. Instructor order etc.

**Comment by rmainseas** [comment]
Found [this](https://orkhan.gitbook.io/typeorm/docs/tree-entities) whilst looking for something else. It seems that TypeORM supports tree-like entities (i.e: one course is the canonical course that all others are "The same as"). It may require some schema changes, but in the long run, it might be worthwhile looking into rather than trying to implement this ourselves.

**Comment by rmainseas** [comment]
So, it looks as though `@TreeParent` and `@TreeChildren` might be what we want here to make this work....

```diff
diff --git a/src/server/course/course.entity.ts b/src/server/course/course.entity.ts
index aa3e8b51..0bff3e37 100644
--- a/src/server/course/course.entity.ts
+++ b/src/server/course/course.entity.ts
@@ -7,6 +7,9 @@ import {
   Index,
   BeforeInsert,
   BeforeUpdate,
+  TreeParent,
+  TreeChildren,
+  Tree,
 } from 'typeorm';
 import { TERM_PATTERN, IS_SEAS } from 'common/constants';
 import { BaseEntity } from '../base/base.entity';
@@ -22,6 +25,7 @@ import { Area } from '../area/area.entity';
 
 @Entity()
 @Index(['prefix', 'numberInteger', 'numberAlphabetical'])
+@Tree('materialized-path')
 export class Course extends BaseEntity {
   /**
    * The long title for the course
@@ -197,6 +201,12 @@ export class Course extends BaseEntity {
   )
   public area: Area;
 
+  @TreeParent()
+  public parent: Course;
+
+  @TreeChildren()
+  public children: Course[];
+
   /**
    * Before inserting or updating a course, this will parse the [[number]]
    * string and save the integer and alphabetical portions in the respective

```

**Comment by Vittorio2015** [comment]
## User interface for Same As course

- Same interface as editing instructors to courses (Courses tab)
- Scroll needed to allow for scalability

### Create new course

Create New Course button on [prototype](https://seas-computing.github.io/course-planner_ux/manage_courses.html)

<img width="599" alt="image" src="https://user-images.githubusercontent.com/12190138/205659204-2dcacc4b-011e-44ae-b9ee-63876d6aa5e2.png">

### Edit course

Edit Course button on [prototype](https://seas-computing.github.io/course-planner_ux/manage_courses.html)

<img width="624" alt="image" src="https://user-images.githubusercontent.com/12190138/205659376-f2de6e8b-dcc6-4936-8a7c-1a4ed0e3969c.png">
