### ISSUE TITLE
Course instance table: Add / Edit view modal basic implementation

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#429]

**Comment by chrxr** [comment]
Hi @rmainseas, considering the discussion here, I think it would be worth breaking these PRs out into four separate tickets. That way we can more easily track progress, and put additional details for each as necessary.

**Comment by jonseitz** [comment]
Agreed on splitting each PR noted above into its own ticket. 

I also think it's important for each of those tickets to list out the specification for the implementation i.e. what data is stored in state, where that state lives, when data is fetched/sent to the server, where the handlers for different buttons will be defined, etc. (The Instructor Modal tickets -- #375 #376 #377 #378 -- are a good template for this)

I'll let @Vittorio2015 weigh in on the UI/UX questions, but it's probably OK to start with that existing flow as a guide and build out those tickets now.
