### ISSUE TITLE
Schedule: Academic year / semester navigation implemented

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#445]
This ticket implements the functionality for a user to be able to select an academic year from a drop-down at the top of the schedule table in order to change the year's data displayed in the table below.

* Get a list of academic years and semesters from the metadata context.
* Present these years/semesters in a drop-down at the top of the table.
* Clicking a year/semester in the drop-down automatically changes the data in the table below to reflect the choice.
  * Refactoring the code in ticket #444 to introduce the passing of the semester and academic year selected in the dropdown to the backend API and refreshing the table with results.
  * When the page is loaded, it will still automatically load the current semester (the default value in the dropdown).

**Comment by natalynyu** [comment]
Tests
* Dropdown is rendered
* Dropdown contains the expected semester values
* Dropdown's default value is the current semester
* When we change the dropdown value, the api arguments reflect the request

**Comment by jonseitz** [comment]
Closed by #448
