### ISSUE TITLE
Course instance table: Persisting views between browser tab refreshes

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#491]
This ticket implements the functionality to save a user's view between browser tab refreshes.

Suggestion is to use Session Storage.

**Comment by jonseitz** [comment]
Might be tricky to test, depending on whether jsdom implements the `SessionStorage` API

**Comment by jonseitz** [comment]
## Current implementation
1. Hard-coded default set of columns is set in state every time the page loads.
2. User can open modal, change columns, close modal.
3. When user leaves page and returns, default columns loaded again.

## New Process
1. Before fetching course content, check for existing data in session storage
2. If there is data, use that. if not, use default columns
3. User opens the modal, update values
4. On close, persist view to `window.sessionStorage` (i.e. call `JSON.stringify`) and update state
5. Data will persist in `sessionStorage` until tab is closed; persists through reloads

## Testing
End-to-end test that goes through the process above, moving between tabs in the app to make sure data persists. Will need to investigate whether jsdom implements the storage API.
7.
