### ISSUE TITLE
Schedule: Pop up room info on all instances

### ISSUE THREAD

**Issue by jonseitz** [seas-computing/course-planner#504]
When clicking on a course in the schedule, each recurrence of the meeting should also pop up with room info. We do not necessarily need to replicate the multi-popover feature for screen readers

**Comment by jonseitz** [comment]
Will involve changing the state value used to track which session has been clicked. Will also need work on tests to handle multiple occurrences (also adding those to the test data, potentially)

**Comment by Vittorio2015** [comment]
## Accessibility review of each course pop-up with room info in "[Schedule](https://planning-qa.seas.harvard.edu/courses/schedule)"

### Monday 9 am schedule

As the focus is moved on a course via the tab key, the screen reader reads "AC 209b on Monday, 9:00 AM to 10:15 AM in 1414 Massachusetts Avenue 437"

<img width="114" alt="image" src="https://user-images.githubusercontent.com/12190138/175108928-6974c104-66a0-4cb5-9c80-08056558875e.png">
