### ISSUE TITLE
Schedule: Fix course numbers appearing outside the bounds of the block

### ISSUE THREAD

**Issue by jonseitz** [seas-computing/course-planner#526]
On the [Spring 2020 view of the Schedule](https://planning-qa.seas.harvard.edu/courses/schedule), some prefix blocks are not large enough to contain all the course numbers. Should we change the font size, or implement some other fix here?

Vittorio to provide a mockup.

**Comment by Vittorio2015** [comment]
## Prefix block overflow

Current "Schedule", Sprint 2020, Tuesday, 10:30 am:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/12190138/175106034-fbbfa71e-3f07-4488-bdb8-d4596ba78174.png">

Adding `overflow: scroll;` to course prefix div class

```
div.sc-bQdRvg {
    overflow: scroll;
}
```
![image](https://user-images.githubusercontent.com/12190138/175105292-f85f7815-0824-4500-b289-85d7f7ea80f8.png)
