### ISSUE TITLE
UI Mockup: New Room Admin Interface

### ISSUE THREAD

**Issue by jonseitz** [seas-computing/course-planner#541]
Following our demo meeting, Users requested ability to add/edit rooms. We decided this would be best handled with a new Admin table (e.g. Course Admin, Faculty Admin). Table should include:

- Campus
- Building
- Room Name
- Capacity

Should also have an interface for adding and editing rooms (via Modal) to edit all fields in room, building, and campus.

**Comment by Vittorio2015** [comment]
## Draft 1
  - [ ] Inspired by the Faculty Admin tab
  - [ ] Campus, Building, Room name, Capacity table headers
  - [ ] Column filters
  - [ ] Modal for creating a new room
  - [ ] Modal for editing each room

### [Room Admin tab prototype](https://seas-computing.github.io/course-planner_ux/manage_room.html) 

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/12190138/179839048-124b88fe-a0cd-40da-ac8f-77cd12b1f7fd.png">

### Create New Room modal

<img width="730" alt="image" src="https://user-images.githubusercontent.com/12190138/179839159-a9d98efd-8529-4446-9cf5-c51c451348d9.png">


### Edit room modal

<img width="766" alt="image" src="https://user-images.githubusercontent.com/12190138/179839216-b994ae83-d00e-4874-bacb-c3b00560e9ed.png">

### Questions

- Are filters needed for all columns?
- Edit room modal - `value` values don't show in input forms
