### ISSUE TITLE
Room Admin: Create Room Modal

### ISSUE THREAD

**Issue by jonseitz** [seas-computing/course-planner#568]
Modal for creating a new Room, with options to create new campus and building. May be re-used for the edit interface in later ticket. When clicking "Create new Room", it will start with a blank form. 

The editable fields will be:

 - Campus, with the option to create a new campus
 - Building, with the option to create a new building
 - Room Number, plain text field
 - Capacity, plain text field (positive, numeric)

User must fill in the campus before filling in Building, and must fill in Building before filling in Room name. Changing any earlier data will clear the later data.

Buttons will be:

- Cancel
- Save

The modal should warn you if you cancel with unsaved changes.

When saving, should send a `POST` request to the server, which will create the new room after ensuring it is not a duplicate. When complete, it should return the new `Room:Building:Campus` object.

The Campus and Building dropdowns will be populated from the list of campuses and buildings fetched in the metadata

### [Team feedback mockups](https://github.com/seas-computing/course-planner/issues/568#issuecomment-1289233620)

**Comment by jonseitz** [comment]
## Testing

Can be tested as part of the suite for the Room Admin page

- Edit Modal
  - [ ] ! Wait for the Modal to appear on the page
  - [ ] Make sure the Room name appears in the header
  - [ ] Make sure the existing room fields are pre-populated
  - [ ] Make sure browser focus shifts to the modal header
- Create Modal
  - [ ] ! Wait for the Modal to appear on the page
  - [ ] Make sure the creating new room text appears in the header
  - [ ] Make sure the fields are all blank
- Cancel Behavior
  - [ ] ! Wait for the Modal to appear on the page
  - [ ] Make sure modal closes immediately if data hasn't been modified
  - [ ] Make it shows the prompt window, if data has been modified.
  - [ ] When Modal closes, focus should shift back to the button

**Comment by Vittorio2015** [comment]
## Room Admin UI

#### Question
Where to place "delete room"? Within the edit room modal it will allow this action to be more deliberate. On the table it would be more direct, and warning popup would prevent casual selection.

### Room Admin table mockup
<img width="749" alt="room-admin-table" src="https://user-images.githubusercontent.com/12190138/193670756-f5d52923-35d3-4363-ad6c-4b8b996c5213.png">

### Create new room modal mockup
<img width="1494" alt="room-admin-create-modal" src="https://user-images.githubusercontent.com/12190138/193670869-5d2b99f1-f2b1-4b87-a2df-a36e929f9f17.png">

### Edit room modal mockup
<img width="1495" alt="room-admin-edit-modal" src="https://user-images.githubusercontent.com/12190138/193670970-ef9408d8-0477-4c7b-86de-0c2a9617e254.png">

**Comment by Vittorio2015** [comment]
## Team feedback

### Room Admin table mockup
- Add room capacity column

### Create new room modal mockup
- Disable Building section until campus is selected

### Edit room modal mockup
- Disable Building section until campus is selected
- Add explanatory text indicating campus selection within Building section
- Add "Delete room" button
- Add confirmation content upon selection of "Delete room" button

**Comment by Vittorio2015** [comment]
## User flow

### User flow when creating a new room
[Source file on Google Drive](https://docs.google.com/drawings/d/1vfbzdPJ_5aUp2xedKZXp5BmfnDECFEn8gVR9J25ospI/edit?usp=sharing)

![image](https://user-images.githubusercontent.com/12190138/195185062-540ac0bb-dd62-49fb-819e-7931fc84a847.png)

**Comment by Vittorio2015** [comment]
## Team feedback

### Creating new room modal

- Streamline user flow, MVP approach
- Add capacity
- Room number only (no noun)
- Remove data when building or campus is changed
- Validation only upon submitting
   - Appropriate casing? 
- Intro paragraph in place of "Note:" text below each field

### Editing existing room modal

- No need to change campus and building; just room number and capacity.

**Comment by Vittorio2015** [comment]
## Edit existing room modal interface mockup

### Just opened modal

- Building and room name in modal heading
- No Campus or building info

<img width="650" alt="image" src="https://user-images.githubusercontent.com/12190138/196949462-de82ef8f-4788-41e3-b408-fe31422b896d.png">

### Error note upon submitting existing new room

<img width="650" alt="image" src="https://user-images.githubusercontent.com/12190138/196951176-a2995bf7-e0a8-4f12-81d8-7b3e728b2c3b.png">

**Comment by Vittorio2015** [comment]
##. Edit existing room name modal interface mockup

### Selected edit room edit button
- Building and room name in modal heading
- Disabled campus and building info

<img width="649" alt="image" src="https://user-images.githubusercontent.com/12190138/196979232-40512dd7-a79f-4c85-9708-7ebf7f93e3b8.png">


### Error note upon submitting existing new room name

- Error only upon submitting existing room name. No validation on capacity.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/12190138/196978963-d92e20e2-89c4-428d-b6f5-82fe159988de.png">

**Comment by Vittorio2015** [comment]
# Final recommendations

## Create New Room - Create a new campus

### Error note upon submitting existing campus

- If existing campus name, remove values in building, room name, and room capacity

![image](https://user-images.githubusercontent.com/12190138/196957548-c333b9f5-a63a-4d11-9e42-5bd6f3e413e0.png)

## Create New Room - Create a new building

### Error note upon submitting existing building

- If existing building name, remove values in room name, and room capacity

<img width="639" alt="image" src="https://user-images.githubusercontent.com/12190138/196957160-787bfe22-7cf0-4795-aecb-6d2ec4724594.png">


## Edit existing room name modal interface mockup

### Selected edit room edit button
- Building and room name in modal heading
- Disabled campus and building info

<img width="649" alt="image" src="https://user-images.githubusercontent.com/12190138/196979232-40512dd7-a79f-4c85-9708-7ebf7f93e3b8.png">


### Error note upon submitting existing new room name

- Error only upon submitting existing room name. No validation on capacity.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/12190138/196978963-d92e20e2-89c4-428d-b6f5-82fe159988de.png">

**Comment by Vittorio2015** [comment]
## Nov. 3 '22 demo and users' feedback

No more "Create a new campus", just "Select an existing campus"

**Comment by jonseitz** [comment]
Closed by #579
