### ISSUE TITLE
Clean up spacing of Schedule Filters

### ISSUE THREAD

**Issue by jonseitz** [seas-computing/course-planner#576]
The design and spacing of the header for the schedule needs to be cleaned up, as in [the prototype](https://seas-computing.github.io/course-planner_ux/schedule.html).

@Vittorio2015 to [update prototype to make schedule dropdown more prominent)](https://github.com/seas-computing/course-planner/issues/576#issuecomment-1289593645).

**Comment by jonseitz** [comment]
## Testing

Changes should only be in CSS, so tests should still pass as expected. Potentially could be issues if tests are traversing/navigating DOM trees.

**Comment by Vittorio2015** [comment]
## Prominent academic year dropdown

- Moved Undergraduate and Graduate checkboxes to the left
- Center aligned academic year label and dropdown
- Increased font size

Source: https://seas-computing.github.io/course-planner_ux/schedule.html

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/12190138/197625384-f39bd103-1f1c-4e59-88e9-a72c1b35cdb3.png">

**Comment by jonseitz** [comment]
Closed by #588
