### ISSUE TITLE
Room Schedule: Clean up inputs above schedule

### ISSUE THREAD

**Issue by jonseitz** [seas-computing/course-planner#584]
The current Room Schedule page has a small semester dropdown and a very large room Combobox. Those should be more balanced at the top of the page, similar to other Pages in the app.

**Comment by Vittorio2015** [comment]
## UI recommendations

### Current work in progress of Rooms Schedule

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/12190138/206269937-717f015f-c770-4f50-ae64-2572fe5295c9.png">


### Proposed layout for Room Schedule

[Commented code from Urji](https://github.com/seas-computing/course-planner_ux/blob/master/kanban-584/room-schedule.html)  (i.e., `<!-- Urji - ... -->`)

- Unwrapped "Select Semester" label like in the [Schedule tab](https://planning-qa.seas.harvard.edu/courses/schedule)
- Align center room selection
- Questions to team
     1. Shall form labels be above input and drop downs? See [Course tab](https://planning-qa.seas.harvard.edu/courses/courses) and  [Faculty tab](https://planning-qa.seas.harvard.edu/courses/faculty).
     2. Shall default view with all displayed rooms? See populated calendar in [Schedule tab](https://planning-qa.seas.harvard.edu/courses/schedule)

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/12190138/206270073-8f361b2a-24e5-41a1-9676-7fd18420358c.png">
