### ISSUE TITLE
Courses instance controller - initial GET

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#98]
API route to deliver Courses interface DTO object. Initial load delivers current default academic year.

  - Client will initially request courses with the query parameter of 'year', which will be the current academic year determined by local user's date.
  - GET request may need additional filtering and expanding to construct the response model.

  - [x] API route should expect a 'year' parameter
  - [x] Server returns all courses
    - Within each course is queried academic year's course instances
    - Response will include retired courses which will be filtered on the front-end.
  - [x] If year parameter is not present then return all objects (for the purpose of background loading additional academic years.
  - [x] Docs
  - [x] Tests

**Comment by jonseitz** [comment]
Resolved by #211
